---
binding:
  - id: discord
    links:
      "/onramp/discord/{i}/out": [
          # Filter bot commands
          "/pipeline/nobot/{i}/in",
          # debugging
          # "/pipeline/system::passthrough/{i}/in",
        ]
      "/pipeline/system::passthrough/{i}/out":
        ["/offramp/system::stdout/{i}/in"]
      "/pipeline/nobot/{i}/out": [
          # setup plugin
          "/pipeline/setup/{i}/in",
          # rules plugin
          "/pipeline/roles/{i}/in",
          # code of conduct plugin
          "/pipeline/code_of_conduct/{i}/in",
          # inclusivity plugin
          "/pipeline/inclusivity/{i}/in",
          # welcome plugin
          "/pipeline/welcome/{i}/in",
          # jokes plugin
          "/pipeline/jokes/{i}/in",
        ]
      "/pipeline/setup/{i}/out": [
          # debugging
          # "/offramp/system::stdout/{i}/in",
          "/onramp/discord/{i}/out",
        ]
      "/pipeline/roles/{i}/out": [
          # debugging
          # "/offramp/system::stdout/{i}/in",
          "/onramp/discord/{i}/out",
        ]
      "/pipeline/code_of_conduct/{i}/out": [
          # debugging
          # "/offramp/system::stdout/{i}/in",
          "/onramp/discord/{i}/out",
        ]
      "/pipeline/inclusivity/{i}/out": [
          # debugging
          # "/offramp/system::stdout/{i}/in",
          "/onramp/discord/{i}/out",
        ]
      "/pipeline/jokes/{i}/out": [
          # debugging
          # "/offramp/system::stdout/{i}/in",
          "/onramp/discord/{i}/out",
        ]
      "/pipeline/welcome/{i}/out": [
          # debugging
          # "/offramp/system::stdout/{i}/in",
          "/onramp/discord/{i}/out",
        ]

mapping:
  /binding/discord/01:
    i: "01"
